approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

packageExtensions:
  swagger-jsdoc@*:
    peerDependencies:
      openapi-types: "*"

yarnPath: .yarn/releases/yarn-4.17.1.cjs
